n = input('Digite algo! ')
print("qual o tipo",type(n))
print("e um numero",n.isalnum())
print("e um alfanumerico",n.isalpha())
print("esta no padrao ascii?",n.isascii())
print("e um decimal",n.isdecimal())
print("e um digito",n.isdigit())
print("e um indentifier",n.isidentifier())
print("esta em minusculo",n.islower())
print("e um numero",n.isnumeric())
print("e printavel",n.isprintable())
print("e um title",n.istitle())
print("esta em maiusculo",n.isupper())
print("e um espaço",n.isspace())
dfas

